### ISSUE TITLE
Seeing error when using latest emscripten

### ISSUE THREAD

**Issue by kevodwyer** [ptitSeb/stuntcarremake#13]
I ran into problems attempting to run stuntcarremake after building it 

Using gl4es master from 23 May 2020 - I saw the changes merged on 23 April 2020 (https://github.com/ptitSeb/gl4es/pull/162/files)

And against
Emscripten v1.39.16: 15 May 2020

I built gl4es using the emscripten target
And then built this project after setting:
EMSCRIPTEN=1 in the makefile

I get the generated files in /docs

However when I attempt to execute in browsers chrome/firefox/safari I get the same error.
After the console lines:
LIBGL: Using GLES 2.0 backend
LIBGL: Hardware test disabled, nothing activated..
I see:
exception thrown: TypeError: Cannot read property 'getParameter' of undefined,TypeError: Cannot read property 'getParameter' of undefined
    at emscriptenWebGLGet
    at _emscripten_glGetIntegerv

Also went back and tried a slightly older version of emscripten, but again same error.
Emscripten v1.39.10: 09 March 2020

I was wondering if you could confirm if you see the same issue?

**Comment by ptitSeb** [comment]
I need to try. I may have broken something in gl4es side.

**Comment by ptitSeb** [comment]
Ok, I have reproduce the issue. I fixed it with a commit on gl4es. So update everything and it should work fine.

**Comment by kevodwyer** [comment]
Brilliant! Thank you.
