### ISSUE TITLE
Text display corrupt with SDL=2

### ISSUE THREAD

**Issue by tikkel** [ptitSeb/stuntcarremake#18]
When i compile with SDL=2 then the text display is corrupt.
With SDL=1 it is all fine.
(under Ubuntu 22.10)
![grafik](https://user-images.githubusercontent.com/37618583/211798925-5d83d861-8457-4c71-acaf-2828f2467e75.png)

**Comment by tikkel** [comment]
I have found a solution! Only 1 gl-Command is needed ...

glPixelStorei(GL_UNPACK_ROW_LENGTH, surf->pitch / surf->format->BytesPerPixel);

in dx_linux.cpp in function  DXUTTextHelper::CDXUTTextHelper()
`
char text[2] = {(char)(i * 16 + j), 0};
			SDL_Surface *surf = TTF_RenderText_Blended(font, text, forecol);
			if (surf)
			{
				m_as[i * 16 + j] = surf->w;
				/* there is a problem with newly libsdl2_ttf, glPixelStorei() helps!
				/  source: https://discourse.libsdl.org/t/sdl-ttf-2-0-18-surface-to-opengl-texture-not-consistent-with-ttf-2-0-15/34529/3 */
				glPixelStorei(GL_UNPACK_ROW_LENGTH, surf->pitch / surf->format->BytesPerPixel);
				glTexSubImage2D(GL_TEXTURE_2D, 0, j * m_fontsize, i * m_fontsize, surf->w, (surf->h >= m_fontsize) ? m_fontsize - 1 : surf->h, GL_RGBA, GL_UNSIGNED_BYTE, surf->pixels);
				SDL_FreeSurface(surf);
			}
			else
			{
				m_as[i * 16 + j] = m_fontsize / 2;
			}
`

**Comment by vanfanel** [comment]
@tikkel This issue is now fixed, feel free to close this.
