### ISSUE TITLE
Hard mode?

### ISSUE THREAD

**Issue by michael-heerdegen** [ptitSeb/stuntcarremake#6]
Hi,

thank you for this - loved to play this game on Amiga.

FWIW, when you won the original game, you got access to a hard mode - the main differences where (1) everything got a light blue color scheme, (2) your car was much faster and (3) difficulty got insane.

Dunno how hard it would be to add that.  I can only say that it was very cool to play that.

Oh, and could there be a "race won" message when you win a race?  The first times I won a race I thought the game crashed because the game just stopped for no apparent reason.

Thanks, Michael.

**Comment by ptitSeb** [comment]
Yes, in career mode, there is the "super league" or something like that (with the blue theme track and super car). I plan to add career mode (for now, this is just training), with that hard mode, but I haven't started working on that yet.

About the message, there should be one, I check (or maybe I'll add the win/loose/break graphics).

**Comment by michael-heerdegen** [comment]
Fine, thanks for your work.

**Comment by michael-heerdegen** [comment]
FWIW, the messages (race won or lost) seems to be there (only) sometimes, most of the time I get none.

**Comment by ptitSeb** [comment]
"Hard mode" is implemented (press L durring Track selection to swith SuperLeague / Normal League)

I have worked on Win/Loose screen (but I always have the text written on my side).

**Comment by michael-heerdegen** [comment]
ptitSeb <notifications@github.com> writes:

> "Hard mode" is implemented (press L durring Track selection to swith
> SuperLeague / Normal League)

Wow - great!

> I have worked on Win/Loose screen (but I always have the text written
> on my side).

Could it be that it is dependent on the monitor configuration and/or
full-screen mode?  Today I played on my Laptop without external monitor
on, and I always got the Win/Loose message (played three or four
tracks).  Oh, maybe the message is just truncated - I have the
impression that the whole screen is truncated (at the bottom) when I
play full screen on my large VGA monitor.


Michael.

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> > "Hard mode" is implemented (press L durring Track selection to swith
> > SuperLeague / Normal League)
>
> Wow - great!

Yip - works great.  Little Ramp is unwinnable, as I remember.  Only the
Tachometer looks a bit strange.  I don't care.

> Oh, maybe the message is just truncated - I have the impression that
> the whole screen is truncated (at the bottom) when I play full screen
> on my large VGA monitor.

Yeah, I really think it's just that what is happening.


Michael.

**Comment by ptitSeb** [comment]
Tachometer should be fixed.

Also, lap info and other stuff not being shown on large screen should be fixed too.

**Comment by michael-heerdegen** [comment]
ptitSeb <notifications@github.com> writes:

> Tachometer should be fixed.
>
> Also, lap info and other stuff not being shown on large screen should
> be fixed too.

Confirmed, that all looks fine now.  Many thanks!

**Comment by ptitSeb** [comment]
Ok, can I close the ticket?

**Comment by michael-heerdegen** [comment]
ptitSeb <notifications@github.com> writes:

> Ok, can I close the ticket?

One question: in the original game, in hard mode, when you start the
"little ramp" and accelerate, you can reach speed 240 before the first
bend - see https://www.youtube.com/watch?v=q7w_0yP5RwU 1:08:15 for
example.  In the remake, that speed is far from reachable.  Nonetheless,
it OTOH seems to take longer to reach the first bend in the original
game.  Is that expected?

**Comment by ptitSeb** [comment]
Mmm, no, strange, I have to check that.

**Comment by ptitSeb** [comment]
Ok, speed display should be good now!

**Comment by michael-heerdegen** [comment]
ptitSeb <notifications@github.com> writes:

> Ok, speed display should be good now!

Thanks, that looks quite good!

Maybe the tachometer shows a bit more than in the original game, but I'm
not sure.

Anyway ... very happy with your changes.  I guess you can close the
ticket.


Many thanks,

Michael.

**Comment by ptitSeb** [comment]
Ok, thanks.

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> Maybe the tachometer shows a bit more than in the original game, but
> I'm not sure.

FWIW, it shows a lot too much.  In normal mode, it is now already quite
easy to accelerate and get the tachometer far beyond overflow.  That
wasn't possible in the original game.  Not sure if the car is too fast
as well.

I think the tachometer shows also too high values in super league mode.

**Comment by ptitSeb** [comment]
Yes indeed. I checked again, and fixed it with e076e364462cf4dd711ce801d74a533c09b22a41. I tried quickly to compare in normal league and super league (LittleRamp, boost and accelerate to the 1st turn) with the video you linked and it seems correct.
