### ISSUE TITLE
Setup Travis CI for build AppImage for Linux

### ISSUE THREAD

**Issue by Symbian9** [ptitSeb/stuntcarremake#8]
Could you setup `.travis.yml` and your repo for build and deploy AppImage packages?

- https://github.com/appimage/appimagekit
  - https://github.com/probonopd/linuxdeployqt
  - https://github.com/probonopd/uploadtool

**Comment by ptitSeb** [comment]
I'll take a look and see if I can push that.

**Comment by ptitSeb** [comment]
Ok, it's done. I hope it works fine for you (it's SDL1.2 build, not sure it's the best choice).

I need to do the same for AppVeyor/Windows now.

**Comment by Symbian9** [comment]
Also, it would be good to add app icon and title name for AppImage.

Cast @probonopd

**Comment by ptitSeb** [comment]
Mmm, The Icon and Title is supposed to be there already. I supposed I messed up the `.desktop` file.

**Comment by ptitSeb** [comment]
Oh wait, you meant the SDL window have no title and no icon. Ah yes, I'll try to add that.

**Comment by probonopd** [comment]
Looks like it refuses to run entirely if there is no sound card, hence our automated test fails and cannot take a screenshot:

```
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: alsa_open_playback: Could not open playback device 'default': No such file or directory
NUMBER_OF_WINDOWS: 0
```

**Comment by ptitSeb** [comment]
I'll try to find some workaround

**Comment by ptitSeb** [comment]
> Also, it would be good to add app icon and title name for AppImage.
> 
> Cast @probonopd

Should be done now.



> Looks like it refuses to run entirely if there is no sound card, hence our automated test fails and cannot take a screenshot:

I hope it works now (not sure how to test in fact).

**Comment by probonopd** [comment]
Thanks, it worked. 👍
